### ISSUE TITLE
final comments

### ISSUE THREAD

**Issue by laserlab** [ubsuny/MLppCollision_CP2P2024#7]
For the final project please address the following issues:

- [x] add a final milestone and add this issue
- [x] add code that show a ML implementation that addresses your documented problem
- [x] compare the ML solution to the solution that is already implemented

**Comment by Pranjal-Srivastava-2023** [comment]
Task 3 in progress.

**Comment by Pranjal-Srivastava-2023** [comment]
Two jupyter notebooks added in repository with detailed codes and plots.

1) dataset_used.ipynb [Explains and visualizes the dataset used.]
2) signal_extraction_xgboost [Separates signal and background by plotting decision boundary plot]

**Comment by Pranjal-Srivastava-2023** [comment]
Done! Final report added to repository. Physics result obtained using ML compared with the known result (reference added in final report).
